[tool.uv]
default-groups = ["dev"]

[tool.uv.sources]
nominal-streaming = { workspace = true }

[tool.uv.workspace]
members = ["py-nominal-streaming/"]

[dependency-groups]
dev = [
  "ipykernel>=7.0.1",
  "mypy>=1.18.2",
  "ruff>=0.14.0",
  "maturin>=1.6,<2.0",
  "nominal>=1.70.0",
  "types-python-dateutil>=2.9.0.20250822",
]

[tool.ruff]
line-length = 120
include = ["py-nominal-streaming/**/*.py", "py-nominal-streaming/**/*.pyi"]
extend-exclude = [".venv", "dist", "build", ".pytest_cache", "__pycache__"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
# See rules and codes: https://docs.astral.sh/ruff/rules/
select = [
    "F",    # pyFlakes
    "E",    # pycodestyle (Err)
    "W",    # pycodestyle (Warn)
    "D",    # pyDocstyle
    "I001", # Isort
    "FIX",  # Flake8-FIXme
    "PL",   # PyLinT
    "NPY",  # NumPY
    "T100", # debugger
]

extend-select = [
    "D417", # no missing arguments
]
ignore = [
    "D100",    # missing-module-docstring
    "D101",    # missing-public-class-docstring
    "D102",    # missing-public-method-docstring
    "D103",    # missing-class-docstring
    "D104",    # missing-package-docstring
    "D203",    # one-blank-line-before-class
    "D205",    # 1 blank line between summary and description
    "D213",    # multiline-summary-docs
    "D400",    # doc line ends in period
    "D401",    # imperative mood
    "D415",    # doc line ends in punctuation
    "FIX002",  # Ignore TODOs
    "PLC0415", # import should be at top-level of a file  
    "PLR0913", # too many arguments
    "PLR2004", # magic values
    "PLW0603", # globals
]

[tool.mypy]
strict = true
packages = ["nominal_streaming"]
pretty = true
warn_unused_configs = true
