[project]
name = "nominal-streaming"
description = "Python bindings for the Nominal Rust streaming client"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Rust",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
# Let maturin source the version from Cargo.toml
dynamic = ["version"]

dependencies = []
[dependency-groups]
dev = [
  "ipykernel>=7.0.1",
  "mypy>=1.18.2",
  "ruff>=0.14.0",
  "maturin>=1.6,<2.0",
  "nominal>=1.70.0",
]

[project.urls]
Homepage = "https://github.com/nominal-io/nominal-streaming"

[build-system]
requires = ["maturin>=1.6,<2.0"]
build-backend = "maturin"

[tool.maturin]
# Put the compiled extension *inside* the Python package folder we add below
module-name   = "nominal_streaming._nominal_streaming"
requires-python = ">=3.10"
profile = "release"
strip = true
manifest-path = "./Cargo.toml"

# Not strictly required, but documents how we expect to build
# Also skips linking against libpython.so
features = ["pyo3/extension-module", "pyo3/abi3-py310"]

# Tell maturin where your pure-Python code lives.
# All files under this directory will be included in the wheel.
python-source = "python"

[tool.uv]
default-groups = ["dev"]

[tool.ruff]
line-length = 120
include = ["python/**/*.py", "python/**/*.pyi"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
# See rules and codes: https://docs.astral.sh/ruff/rules/
select = [
    "F",    # pyFlakes
    "E",    # pycodestyle (Err)
    "W",    # pycodestyle (Warn)
    "D",    # pyDocstyle
    "I001", # Isort
    "FIX",  # Flake8-FIXme
    "PL",   # PyLinT
    "NPY",  # NumPY
    "T100", # debugger
]

extend-select = [
    "D417", # no missing arguments
]
ignore = [
    "D100",    # missing-module-docstring
    "D101",    # missing-public-class-docstring
    "D102",    # missing-public-method-docstring
    "D103",    # missing-class-docstring
    "D104",    # missing-package-docstring
    "D203",    # one-blank-line-before-class
    "D205",    # 1 blank line between summary and description
    "D213",    # multiline-summary-docs
    "D400",    # doc line ends in period
    "D401",    # imperative mood
    "D415",    # doc line ends in punctuation
    "FIX002",  # Ignore TODOs
    "PLC0415", # import should be at top-level of a file  
    "PLR0913", # too many arguments
    "PLR2004", # magic values
    "PLW0603", # globals
]

[tool.mypy]
strict = true
packages = ["nominal_streaming"]
