name: Build and Test Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.x"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}
      - name: Check uv lockfile metadata
        run: |
          if ! uv --directory py-nominal-streaming lock --check; then 
            echo "::error::`uv lock --check` has failed, ensure you have the latest `uv` version installed with `uv self update` and run `uv sync`"
            exit 1
          fi
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          rustflags: ""
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Build bindings and install in dev mode
        run: |
          just python::dev
      - name: Check format
        run: |
          just python::check-format
      - name: Check import order
        run: |
          just python::check-imports
      - name: Static type check
        run: |
          just python::check-types-all
