name: Build and Test Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
          rustflags: ""
      - name: Install Rust Problem Matcher
        run: echo "::add-matcher::.github/rust.json"
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Install rust dependencies
        run: just rust::install
      - name: Build rust crates
        run: just rust::build
      - name: Check rust format
        run: just rust::check
      - name: Run rust Tests
        run: just rust::test
