name: PR structure

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  validate-pr-title:
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install commitlint
        run: npm install -g @commitlint/cli@20 @commitlint/config-conventional@20
      - name: Check PR title (commitlint)
        env:
          # Store in an environment to guard against script injection
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$TITLE" | commitlint --config .github/commitlint.config.js
      - name: Explain title failure
        if: failure()
        env:
          # Store in an environment to guard against script injection
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "🚨 Your PR Title: \"${TITLE}\" did not pass linting" >> $GITHUB_STEP_SUMMARY
          echo "Please update it to follow conventional commit format: https://www.conventionalcommits.org/" >> $GITHUB_STEP_SUMMARY
