name: build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: depot-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set rustup toolchain
        run: rustup default stable
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Build
        run: cargo build
      - name: Check format
        run: cargo fmt --all --check
      - name: Run Tests
        run: cargo test --workspace
